"""Add SIM issuance model

Revision ID: 124fc271ec68
Revises: e0e9c4093c11
Create Date: 2026-07-22 10:49:46.611394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124fc271ec68'
down_revision = 'e0e9c4093c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_issuance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dso_id', sa.String(length=50), nullable=True),
    sa.Column('sim_serial', sa.String(length=100), nullable=False),
    sa.Column('distributor_name', sa.String(length=150), nullable=True),
    sa.Column('order_date', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('order_reference', sa.String(length=100), nullable=True),
    sa.Column('kyc_msisdn', sa.String(length=50), nullable=True),
    sa.Column('served_msisdn', sa.String(length=50), nullable=True),
    sa.Column('kyc_created_on', sa.String(length=50), nullable=True),
    sa.Column('activation_time', sa.String(length=50), nullable=True),
    sa.Column('device_technology', sa.String(length=50), nullable=True),
    sa.Column('recharge_amount', sa.Float(), nullable=True),
    sa.Column('retailer_msisdn', sa.String(length=50), nullable=True),
    sa.Column('promoter_msisdn', sa.String(length=50), nullable=True),
    sa.Column('zone_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_serial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sim_issuance')
    # ### end Alembic commands ###
