"""Add performance snapshot model

Revision ID: 8766b68e1027
Revises: 124fc271ec68
Create Date: 2026-07-22 11:13:54.102111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8766b68e1027'
down_revision = '124fc271ec68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('partner_name', sa.String(length=150), nullable=False),
    sa.Column('contract_status', sa.String(length=100), nullable=True),
    sa.Column('gross_adds', sa.Integer(), nullable=True),
    sa.Column('gross_adds_target', sa.Integer(), nullable=True),
    sa.Column('sim_billing', sa.Integer(), nullable=True),
    sa.Column('sim_billing_target', sa.Integer(), nullable=True),
    sa.Column('active_agents_percent', sa.Float(), nullable=True),
    sa.Column('active_agents_target', sa.Float(), nullable=True),
    sa.Column('back_margin_rate', sa.Float(), nullable=True),
    sa.Column('target_back_margin_rate', sa.Float(), nullable=True),
    sa.Column('primaries_purchased', sa.Float(), nullable=True),
    sa.Column('agent_led_airtime', sa.Float(), nullable=True),
    sa.Column('retailer_self_recharges', sa.Float(), nullable=True),
    sa.Column('total_airtime', sa.Float(), nullable=True),
    sa.Column('projected_commission', sa.Float(), nullable=True),
    sa.Column('total_agents', sa.Integer(), nullable=True),
    sa.Column('active_agents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_snapshots')
    # ### end Alembic commands ###
