"""Remove client credentials from email accounts

Revision ID: a4af274f9be0
Revises: 26cc14b4f396
Create Date: 2026-07-30 17:12:28.219027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4af274f9be0'
down_revision = '26cc14b4f396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_column('client_secret')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_secret', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
