"""Initial database schema

Revision ID: e0e9c4093c11
Revises: 
Create Date: 2026-07-22 09:44:40.386892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e9c4093c11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_number', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=150), nullable=False),
    sa.Column('site', sa.String(length=150), nullable=True),
    sa.Column('tse', sa.String(length=150), nullable=True),
    sa.Column('ama', sa.String(length=20), nullable=True),
    sa.Column('qama', sa.String(length=20), nullable=True),
    sa.Column('qdrso', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    # ### end Alembic commands ###
